---
title: "Private Data Sources for Business Analytics in Entrepreneurship"
subsubtitle: "Source the databases of the Harold B. Lee Library (HBLL) at BYU"
---

```{r}
#| output: false
library(tidyverse)
library(ggthemes)
library(scales)
library(gt)
knitr::opts_chunk$set(echo = TRUE) 
```

```{=html}
<style>
.wrapfig {
    float: right; 
    margin: 0 20px 10px 0; /* adjust space around the image */
    width: 40%; /* adjust image width */
}
</style>
```


The depth and breadth of information can often dictate the boundary between success and failure for founders and their startups. Private data sources are a particular advantage to entrepreneurs who have access to them.  These data sources offer detailed, proprietary insights that are not readily available through public data. They resources encompass a wide array of databases and platforms, each catering to different facets of __market research__, __competitive analysis__, and __consumer behavior__.

## Why Private Data Matters 

Private data sources provide:

- __Detailed Market Insights__: Access to granular data about market trends, industry benchmarks, and consumer preferences.
- __Competitive Edge__: Information from these sources can give businesses a competitive advantage by providing insights that are not accessible to everyone.
- __Risk Mitigation__: Helps in forecasting and mitigating risks by providing detailed historical data and predictive insights.

Entrepreneurs who have access to these sources, and understand how to effectively leverage them, can make informed decisions, anticipate market movements, and tailor their strategies to meet precise market demands.


<br>

## Ethics of Using and Sharing Private Data

### Privacy and Data Governance
As powerful as private data sources are, they come with significant ethical responsibilities, particularly concerning privacy, data governance, and compliance with legal standards.

__Privacy and Confidentiality__: When dealing with private data, it is crucial to ensure the confidentiality and privacy of the information are maintained. Entrepreneurs must be vigilant about:

- __Data Protection Laws__: Complying with local and international data protection laws, such as GDPR in Europe and CCPA in California, which dictate how data should be handled and protected.
- __Consent and Transparency__: Ensuring that data is collected and used transparently, with the consent of all parties involved, particularly when dealing with sensitive information.

::: {.callout-tip title="Use of BYU Library Databases"}

In general, the private databases in the Harold B. Lee Library is freely permitted for use in classroom work.  They generally exclude using the databases for commercial purposes including internships, consulting, and employment in non-BYU companies.  Fortunately for entrepreneurial management majors at BYU, our use is for educational purposes.  There are individual documents in these databases that would sell for thousands of dollars to enterprise customers but are free to you for educational use. While it is possible to abuse your access to these proprietary databases, you should not. 
:::

__Responsible Use of Data__: Ethical use of private data also means using it responsibly:

- __Bias and Fairness__: Being aware of and mitigating any biases in the data that could lead to skewed conclusions or unfair business practices.
- __Accuracy and Integrity__: Maintaining the accuracy and integrity of data by using reputable sources and verifying the information before application.

__Sharing and Distribution__: The sharing and distribution of data must be handled with care to avoid misuse:

- __Confidential Agreements__: Using nondisclosure agreements (NDAs) where necessary to protect sensitive information.
- __Controlled Access__: Limiting data access to only those who need it for legitimate business purposes, thus minimizing the risk of data breaches or leaks.

__Ethical Considerations in Entrepreneurship__: Ultimately, ethical considerations in using private data sources should guide how entrepreneurs collect, analyze, and apply data to ensure that their practices contribute positively to their business without compromising ethical standards.

Understanding and adhering to ethical guidelines when using private data sources is not just about compliance; it's about building trust with customers, partners, and the public. Entrepreneurs who prioritize ethical data practices are better positioned to build sustainable and respected businesses.


<br>

## Industry Trends

---

### ProQuest TDM Studio

ProQuest TDM Studio offers a robust platform for text and data mining (TDM), allowing users to analyze large datasets to uncover new insights and make informed decisions. It is particularly useful for entrepreneurs who need to parse through extensive textual data to extract actionable business intelligence.

::: {.callout-tip title="Use ProQuest TDM Studio at BYU"}
Find content from BYU’s ProQuest database subscriptions and use data visualizations to analyze without coding. You must create an account. Learn more [here](https://proquest.libguides.com/tdmstudio/visualization).  You will need to be logged in to your BYU account and you may need to be on BYU wifi.

__BYU's license with with ProQuest allows only one user at a time for all of campus.  It is recommended that you work in the library with the librarians when you want to use ProQuest TDM Studio.__
:::

#### Features and Capabilities

- **Extensive Data Access**: Users can access a wide range of ProQuest's databases, including historical newspapers, dissertations, scholarly journals, and more, providing a rich source of textual data.
- **Advanced Analytical Tools**: TDM Studio provides tools for natural language processing, sentiment analysis, trend analysis, and more, enabling users to conduct comprehensive analyses of textual data.
- **User-Friendly Interface**: The platform offers a user-friendly interface that allows users with minimal programming skills to perform complex text and data mining tasks.

#### Applications in Entrepreneurship

- **Market Trend Analysis**: Entrepreneurs can analyze news articles, social media posts, and industry reports to identify and track market trends and consumer sentiments.
- **Competitive Intelligence**: By mining competitor data, entrepreneurs can gain insights into competitive strategies and market positioning.
- **Risk Management**: Analyzing historical data can help predict potential market disruptions and assess risks associated with new business ventures.

#### Ethical and Responsible Use

- **Data Privacy**: Users must ensure they comply with data privacy laws and regulations when accessing and analyzing personal or sensitive information.
- **Intellectual Property**: It is crucial to respect the intellectual property rights of the data sources accessed through TDM Studio.

ProQuest TDM Studio is an invaluable resource for entrepreneurs seeking to leverage advanced text and data mining techniques to enhance their business strategies. By providing access to diverse datasets and powerful analytical tools, TDM Studio helps uncover deep insights that can drive innovation and competitive advantage.



<br>

### BizMiner

:::{.callout-tip title="Use BizMiner at BYU"}
BizMiner is a leading online provider of industry financial analysis and market research. Learn more [here](https://app.bizminer.com/search).
:::

BizMiner provides detailed industry-specific financial analysis and market trends data, catering to a wide range of sectors. It stands out for its comprehensive reports that cover industry financial profiles, market analysis, and competitive market benchmarks, making it an invaluable resource for entrepreneurs who need to understand the nuances of their industry deeply.

#### Features and Capabilities

- **Industry Financial Profiles**: Access to detailed financial statements and ratios for over 5,000 industries at local and national levels, which can help entrepreneurs gauge the financial health and performance standards within their sectors.
- **Market Analysis Reports**: Offers insights into market trends, including startup activity, sales growth, and business failure rates, which are crucial for strategic planning and risk assessment.
- **Competitive Benchmarks**: Provides comparative industry data that helps businesses understand their position relative to competitors, highlighting areas for improvement and investment.

#### Applications in Entrepreneurship

- **Strategic Planning**: Entrepreneurs can use BizMiner to identify industry trends and forecast potential shifts, aiding in long-term business planning and resource allocation.
- **Financial Benchmarking**: By comparing their financial metrics against industry standards, entrepreneurs can pinpoint strengths and weaknesses in their business operations, guiding financial strategy and investment decisions.
- **Risk Assessment**: Understanding the failure rates and challenges within an industry helps entrepreneurs develop more robust risk management strategies, potentially avoiding common pitfalls.

#### Ethical and Responsible Use

- **Confidentiality and Accuracy**: Users must ensure the data is used responsibly, maintaining confidentiality where required and verifying the accuracy of the data before making business decisions.
- **Compliance and Fair Use**: Entrepreneurs should adhere to fair use of the data and comply with any licensing agreements associated with BizMiner reports.


BizMiner is a critical tool for entrepreneurs who require depth and precision in their market and financial analysis. With its detailed reports and benchmarking capabilities, BizMiner not only informs better business decisions but also enhances competitive strategy and operational effectiveness.


<br>

### Mergent Key Business Ratios

Mergent Key Business Ratios provides access to critical financial benchmarks and detailed ratio analysis covering a vast range of industries. This tool is designed to deliver in-depth insights into industry and company financials, helping entrepreneurs and students alike understand financial health and performance standards effectively.

:::{.callout-tip title="Use Mergent Key Business Ratios (KBR) at BYU"}
Key Business Ratios on the Web (KBR) provides immediate online access to competitive benchmarking data. This powerful tool lets researchers examine industry benchmarks compiled from D&B’s database of public and private companies, featuring 14 key business ratios (users choose a one-year or three-year set of ratios) for public and private companies in 800 lines of business. Learn more [here](https://www.mergentkbr.com/).
:::

#### Features and Capabilities

- **Comprehensive Financial Data**: Offers exhaustive data on industry-specific financial ratios, essential for assessing operational success and financial health.
- **Ease of Use**: The platform is intuitive and user-friendly, making it accessible even to those new to financial analysis.

##### Industry Reports

Mergent Key Business Ratios' Industry Reports provide comprehensive financial metrics including detailed ratios, variances, and norms across hundreds of industries. These reports are designed to give students a granular look at industry standards and performance metrics.

- **Detailed Financial Metrics**: Each report includes tables and charts of financial ratios and variances, offering a detailed view of industry benchmarks.
- **Interactive Data Presentation**: The tables allow users to hover over financial metrics to see the equations used for calculations, enhancing understanding of how each metric is derived.
- **Visualization Tools**: In addition to tables, users can visualize data through charts that display ratios and norms, making it easier to interpret complex financial data.

While the Industry Reports provide detailed data, they do not offer guidance on interpreting these metrics within broader business or economic contexts. This presents an educational opportunity:

##### Company Reports

Mergent Key Business Ratios' Company Reports provide targeted financial data and ratios for a broad spectrum of companies, offering specific insights into both public and private companies. These reports are designed to enable detailed financial analysis by allowing users to search for companies by various criteria.

- **Targeted Financial Data**: Access detailed financials and ratios for a wide range of companies. Users can perform searches that are not limited to pre-populated lists, allowing for the exploration of less common or smaller entities.
- **Customizable Searches**: Search functionality includes filters such as location, company type, and DUNS Number, making it easier to find specific companies.
- **Enhanced Visualization**: For public companies, the platform provides comprehensive views of the balance sheet, income statement, cash flow, and financial ratios, complete with charts for better visualization.


Users can access extensive financial details for public companies, which include visual representations of financial statements and ratios.

The availability of data for private companies can be limited, with reports often noting "No data available for the selected criteria." This limitation requires users to be mindful of the scope of their research, particularly when dealing with private entities.

##### Industry Ratios

Mergent Key Business Ratios offers a robust analysis of industry-specific financial ratios, providing valuable insights into the solvency, efficiency, and profitability across various industries. This data is crucial for understanding the financial health and trends within specific sectors.

- **Comprehensive Data Span**: The ratios cover an extensive period from 2009 to 2022, allowing users to observe trends and outliers within any given industry.
- **Detailed Quartile Metrics**: The data includes upper, median, and lower quartiles, offering a detailed view of the distribution of financial health within industries. This granular data helps in understanding how different companies within an industry stack up against each other in terms of financial performance.

By examining the change in financial ratios over time, you can identify trends that may indicate improving or deteriorating industry health. The quartile data provides a benchmark for comparing a company's performance against industry averages, helping to pinpoint areas of strength or weakness.

While the data is extensive within a given industry, it does not facilitate comparisons across different industries, which could be useful for broader market analysis. It also does not include explanations for why ratios may vary over the years nor does it suggest how companies might improve their financial metrics. You need to interpret the raw data independently or supplement it with other sources for a more comprehensive analysis.

##### Company Ratios

Mergent Key Business Ratios provides detailed company ratio analyses, including solvency, efficiency, and profitability metrics for companies within specific industries. This feature enables a comprehensive comparison across companies, highlighting differences in financial health and operational performance.

- **Extensive Financial Metrics**: Offers analyses on solvency, efficiency, and profitability for each listed company, aiding in thorough financial scrutiny.
- **Comparative Analysis**: Allows for side-by-side comparisons of financial ratios across companies in the same industry, which is invaluable for benchmarking.
- **Historical Data Trends**: Includes multiple years of financial data for some companies, helping users track performance trends and identify potential growth or decline patterns.

Compare your company's financial health against others in the industry to determine competitive standing. Analyzing historical data helps predict future trends and potential financial trajectories of companies within the industry.

Although the tool provides basic solvency and efficiency ratios, it lacks deeper profitability metrics such as Return on Equity (ROE), Gross Profit Margin, and Net Profit Margin, which are crucial for comprehensive financial analysis.

#### Utilizing Mergent for Business Analysis

- **Industry and Company Specific Reports**: Students can explore detailed reports on industries or individual companies, which provide valuable insights into financial trends, performance metrics, and risk factors.
- **Customizable Financial Reports**: Allows users to generate tailored reports focusing on specific financial metrics, enhancing their understanding of financial structures and outcomes.


Mergent Key Business Ratios is an essential tool for anyone involved in business analysis, from students beginning their journey in entrepreneurship to seasoned professionals. By providing detailed industry and financial insights, Mergent helps users make informed decisions based on robust data, thus enhancing their strategic planning capabilities.


### IBISWorld

IBISWorld is a comprehensive industry research platform that provides detailed reports on a wide range of industries. It offers market conditions, industry benchmarks, forecasts, and competitive analysis.

#### Features and Capabilities

- **Industry Reports**: Detailed insights into market size, trends, growth drivers, and industry performance.
- **Forecasts**: Five-year forecasts based on historical data, providing future market trends.
- **Key Players**: Information on major companies within each industry and competitive dynamics.
- **Risk Ratings**: Industry-specific risk scores, which are useful for understanding market volatility.

#### Applications in Entrepreneurship

Entrepreneurs can use IBISWorld to:

- Understand the competitive landscape of an industry before launching a product.
- Analyze trends in their specific industry, helping them anticipate challenges or opportunities.
- Identify key players and potential partnerships or competition.
- Forecast market conditions to time product launches or expansions effectively.

<!-- #### Ethical and Responsible Use
Ensure that data sourced from IBISWorld is used for educational and strategic purposes within the bounds of BYU's guidelines. Avoid sharing proprietary information externally and be cautious of data misrepresentation in strategic planning.-->


### Statista

Statista provides access to quantitative data across a wide range of industries, regions, and market sectors. It is particularly known for its easy-to-use visualizations and quick data snapshots.

#### Features and Capabilities

- **Statistical Data**: Offers statistics on industries, companies, and countries, with easy-to-read charts and infographics.
- **Consumer Surveys**: Includes consumer opinions and trends for specific product categories.
- **Reports**: Industry, company, and market outlook reports, often updated annually.
- **Global Coverage**: Data from over 170 industries across the globe.

#### Applications in Entrepreneurship

Entrepreneurs can leverage Statista for:

- Quick insights into consumer behavior and industry performance using visual data representations.
- Supporting business plans and pitches with reliable, up-to-date statistics.
- Benchmarking performance against industry averages.
- Identifying international market opportunities with comparative data.


### Frost & Sullivan

Frost & Sullivan specializes in market research and consulting across industries like IT, healthcare, and energy. It provides comprehensive market reports and growth forecasts focused on emerging technologies and market innovations.

#### Features and Capabilities

- **Market Research Reports**: Extensive data on industry trends, technological innovations, and market drivers.
- **Growth Consulting**: Strategic consulting services focused on market expansion and product innovation.
- **Competitive Benchmarking**: Data on industry leaders and emerging competitors.
- **Forecasts**: Long-term forecasts on market trends and consumer behavior, with a focus on technology-driven industries.

#### Applications in Entrepreneurship

Entrepreneurs in technology or innovation sectors can use Frost & Sullivan to:

- Stay ahead of industry trends by tracking emerging technologies.
- Benchmark against competitors and industry leaders.
- Make data-driven decisions about product development and market entry.
- Access consulting resources to refine growth strategies.

#### Ethical and Responsible Use
The proprietary data from Frost & Sullivan is valuable and sensitive. Ensure it is used in accordance with BYU's guidelines, particularly for educational purposes, and refrain from sharing sensitive insights externally.

<br>


## Consumer Trends

---

### Social Explorer

Social Explorer is an advanced demographic analysis tool that offers extensive data visualization and mapping capabilities. It is designed to aid in the understanding of demographic changes and their potential impacts on business opportunities, making it particularly valuable for entrepreneurship education.

::: {.callout-tip title="Use Social Explorer at BYU"}
Social Explorer is an online research tool designed to provide quick and easy access to current and historical census data and demographic information. The easy-to-use web interface lets users create maps and reports to better illustrate, analyze and understand demography and social change.  Learn more [here](https://www.socialexplorer.com/a9676d974c/explore).
:::

#### Features and Capabilities

- **Lecture Launchers**: Social Explorer includes specialized resources such as "Developing New Businesses Based on COVID-19 Opportunities" and "Population Change and Opportunities for Entrepreneurship," which are designed to inspire creativity and entrepreneurial thinking.
- **Training Modules**: Offers comprehensive training on how to utilize the platform effectively, covering aspects such as data masking, filtering, and various types of visualizations.

#### Applications in Entrepreneurship

- **Market Analysis Projects**: Students can use Social Explorer to conduct detailed market analyses by selecting a city or region, examining key demographics, income levels, and business environments to identify opportunities and challenges for hypothetical business ventures.
- **Location Strategy for Brick-and-Mortar Ventures**: Enables students to choose optimal locations for potential businesses based on in-depth analysis of demographic data, local competition, and economic factors.
- **Community Problem-Solving**: Students can design projects that address specific community issues identified through Social Explorer's data, proposing business solutions that cater to health, education, or income gaps.
- **Comprehensive Mapping Capabilities**: Social Explorer provides various maps, including crime data, election data, census data, U.S. business patterns, and opportunity zones, which are invaluable for spatial analysis in entrepreneurship.
- **Historical and Contemporary Data**: Offers access to over 500,000 data indicators and historical data dating back to 1790, enabling long-term trend analysis and contextual understanding of demographic shifts.

Social Explorer stands out as a powerful tool for entrepreneurs and educators, offering deep insights into demographic trends and the potential impacts on business opportunities. Its rich datasets and visualization tools make it an essential resource for anyone involved in the study or practice of entrepreneurship.

<br>

### IPUMS

#### Overview of IPUMS

IPUMS (Integrated Public Use Microdata Series) offers a comprehensive array of census and survey data integrated across time and space, making it a valuable tool for in-depth demographic and socio-economic research. While it may not be as intuitive as some other databases, with guided exploration, it can provide significant insights into various factors that influence business decisions.

::: {.callout-tip title="Use IPUMS at BYU"}
Access microdata from the US Census (1790-2010) and American Community Survey (2000-on). Learn more about IPUMS  [here](https://usa.ipums.org/usa/) and [here](https://youtu.be/S-3ce5D8l2A?si=MgE1UQ15I8ADSPqJ) for a BYU HBLL tutorial.
:::


#### Educational Value and Data Accessibility

- **Extensive Data Integration**: IPUMS integrates data from censuses and surveys around the world, providing a longitudinal perspective that is crucial for understanding changes over time and differences across locations.
- **Rich Documentation**: The platform is well-documented, making it easier for researchers to understand the context and application of the data they are examining.

#### Practical Applications in Entrepreneurship

- **Demographic and Economic Analysis**: Conduct detailed analyses of demographic trends, labor market conditions, and other socio-economic factors that are crucial for market analysis and business planning.
- **Custom Data Extraction**: Build custom data extracts to answer specific entrepreneurial questions, such as analyzing the age demographic of potential customer bases in particular communities.


While IPUMS presents some challenges in terms of user friendliness and data specificity for direct business applications, it remains an excellent resource for understanding broad demographic and economic trends. Educators can leverage IPUMS to teach students how to integrate demographic data with other business insights, fostering a more comprehensive approach to entrepreneurship and strategic planning.


### Simmons
Simmons Research provides deep insights into consumer behavior, psychographics, and media consumption patterns, helping businesses understand the attitudes and preferences of their target audiences.

::: {.callout-tip title="Use Simmons at BYU"}
Detailed consumer survey data. Where else can you cross-tabulate age, media consumption, political viewpoints, and the frequency of Snickers bar consumption? Tutorial for this database can be viewed [here](https://youtu.be/K6gv38xyXIM?si=d1qoHmKJhYKvJEDC) and many more [here](https://www.youtube.com/user/iLearningServices/search?query=simmons). *May NOT be used for commercial use, consulting, or outside research projects.*
:::

#### Features and Capabilities

- **Consumer Behavior Data**: Detailed insights into consumer lifestyles, media habits, and purchase behaviors.
- **Psychographics**: Information on consumer attitudes, values, and interests.
- **Media Usage**: Data on how consumers interact with different media platforms, including television, digital, and social media.
- **Segmented Data**: Ability to break down data by demographic, geographic, and psychographic segments.

#### Applications in Entrepreneurship
Entrepreneurs can use Simmons to:

- Tailor marketing strategies to specific consumer segments based on lifestyle and media consumption.
- Identify key psychographic profiles to align products and services with consumer attitudes.
- Optimize media buying strategies by understanding where target audiences are most active.
- Develop more personalized messaging and product offerings for different consumer groups.

#### Ethical and Responsible Use
Simmons data provides intimate insights into consumer behavior, and it is critical to use this data responsibly. Entrepreneurs should avoid invasive marketing strategies and respect consumer privacy when utilizing psychographic data.



### General Social Survey (GSS) - University of Chicago
The General Social Survey, conducted by the University of Chicago, is one of the most comprehensive sources of public opinion and social behavior data in the United States. It tracks demographic trends and attitudes toward various social, political, and economic issues.

#### Features and Capabilities

- **Longitudinal Data**: Decades of data tracking social attitudes, behaviors, and demographics in the U.S.
- **Public Opinion Data**: Insights into how Americans feel about political, social, and economic issues.
- **Demographic Segmentation**: Data segmented by age, race, gender, income, education, and other demographic factors.
- **Social Trends**: Analysis of long-term social trends in areas like work, family, religion, and politics.

#### Applications in Entrepreneurship
Entrepreneurs can use GSS data to:

- Understand societal trends that may impact consumer preferences and market opportunities.
- Analyze public opinion to predict shifts in consumer behavior or regulatory changes.
- Explore demographic trends to identify underserved markets or emerging social movements.
- Develop products or services that align with long-term social and cultural shifts.

#### Ethical and Responsible Use
GSS data is publicly accessible, but it should be used ethically to respect privacy and avoid misrepresenting public opinion. Ensure that this data is used to inform socially responsible business decisions.




<br>

## Competitor Analysis

--- 

### PitchBook

PitchBook is a comprehensive data provider that offers in-depth information on the global capital markets, focusing on private equity, venture capital, and mergers & acquisitions. It is designed to help users conduct rigorous financial research, competitive analysis, and market trend analysis.

::: {.callout-tip title="Use Pitchbook at BYU"}
Must first create a login using a byu.net email address. A byu.net email alias can be created at [https://my.byu.edu](https://my.byu.edu) under Communication using the Email Alias Manager. Research and analyze companies, deals, funds, investors and service providers across the entire private investment lifecycle. For educational use at BYU only. Learn more [here](https://my-pitchbook-com.byu.idm.oclc.org/).
:::

#### Features and Capabilities

- **Extensive Company Databases**: PitchBook provides detailed profiles for companies worldwide, including financials, key personnel, investments, and fundraising history.
- **Investment Insights**: Tracks investments and deals across the private equity and venture capital landscapes, giving users insights into industry trends, investment returns, and deal flow.
- **Market Analysis Tools**: Offers advanced tools for analyzing market trends, benchmarking, and producing detailed forecasts and valuations.

#### Practical Applications in Entrepreneurship

- **Startup Valuation and Fundraising**: Entrepreneurs can use PitchBook to assess their startup's valuation against comparable companies, understand funding landscapes, and identify potential investors.
- **Competitive Intelligence**: Provides comprehensive data that can help entrepreneurs understand their competition's funding history, investment strategy, and market positioning.

The depth and breadth of information provided can be overwhelming for new users, requiring a steep learning curve to navigate effectively.

PitchBook is an essential tool for anyone involved in the finance and investment sectors, particularly useful for entrepreneurs looking to navigate venture capital, private equity, and M&A landscapes. It empowers users with the data needed to make informed decisions, though its full utility might be constrained by access costs and the complexity of its data systems.

### Preqin
Preqin is a leading provider of data on alternative assets, including private equity, venture capital, hedge funds, and real estate.

#### Features and Capabilities

- **Private Market Data**: Extensive information on private equity, venture capital, hedge funds, and real estate investments.
- **Fund Performance**: Data on fund performance, investor mandates, and capital allocations.
- **Investor Profiles**: Detailed profiles of institutional investors, including investment preferences and capital commitments.
- **Deal Tracking**: Insights into recent deals, exits, and mergers across the private markets.

#### Applications in Entrepreneurship
Entrepreneurs can use Preqin to:

- Identify potential investors or partners in venture capital or private equity.
- Track investment trends in their industry to understand where capital is flowing.
- Benchmark their business against private market competitors.
- Analyze the performance of private market funds and track competitors' investment strategies.

#### Ethical and Responsible Use
Preqin provides access to sensitive data on private market investments. Entrepreneurs should ensure that this data is used responsibly for internal analysis and strategy, adhering to ethical guidelines for competitive intelligence.


### PrivCo

PrivCo is a financial data provider that specializes in private company information, offering insights into company financials, funding, and acquisition activity.

::: {.callout-tip title="Use PrivCo at BYU"}
PrivCo is the premiere source for business and financial data on major, non-publicly traded corporations, including family owned, private equity owned, venture backed, and international unlisted companies. First-time users must create a username.
:::

#### Features and Capabilities

- **Private Company Data**: Detailed financial information on private companies, including revenue, employee size, and funding rounds.
- **Funding & M&A**: Track venture capital investments, private equity deals, and mergers and acquisitions.
- **Industry Comparisons**: Compare financials of companies within specific industries or regions.
- **Growth Indicators**: Data on a company’s growth potential based on funding and operational metrics.

#### Applications in Entrepreneurship

Entrepreneurs can use PrivCo to:

- Analyze competitors in private markets to better position their own ventures.
- Identify potential acquisition targets or investment opportunities.
- Track funding trends and evaluate investment in a specific industry.
- Benchmark against similar companies to gauge growth potential.

#### Ethical and Responsible Use
PrivCo provides sensitive private company data that should be used responsibly, particularly in competitive settings. Ensure that data is only used for internal analysis and business strategy, in accordance with BYU’s ethical guidelines.



### Mergent Online

Mergent Online provides comprehensive financial information on both public and private companies, with historical data, equity pricing, and financial ratios.

#### Features and Capabilities

- **Company Financials**: Detailed balance sheets, income statements, and cash flow data for public companies.
- **Private Company Information**: Limited access to private company data, with a focus on financial performance.
- **Stock and Bond Data**: Historical stock prices and bond performance, useful for investment analysis.
- **Custom Reports**: Generate detailed financial reports with historical data for companies of interest.

#### Applications in Entrepreneurship

Entrepreneurs can leverage Mergent Online to:

- Analyze public company financials to understand industry benchmarks and trends.
- Research competitors’ financial health and growth trajectories.
- Identify potential investors or partners through financial analysis.
- Generate reports that support fundraising efforts or business planning.

### Mergent Intellect

Mergent Intellect provides data on both public and private companies, with additional tools for market analysis and consumer demographics. It integrates data from Dun & Bradstreet to offer robust company profiles.

::: {.callout-tip title="Use Mergent Intellect at BYU"}
Follow the directions in this [video](https://www.youtube.com/watch?v=LqUOLnaWBOI) to create a list of company locations that fit the criteria for competitors.
:::

#### Features and Capabilities

- **Private Company Data**: Access comprehensive company profiles with operational and financial data.
- **Demographics**: Tools for mapping and analyzing demographic data, including consumer spending trends.
- **Company Comparisons**: Compare companies across industries or regions to assess competition.
- **D&B Integration**: Includes data from Dun & Bradstreet for deeper insights into private company operations.

#### Applications in Entrepreneurship

Entrepreneurs can use Mergent Intellect to:

- Research both public and private competitors in depth.
- Identify potential partners or acquisition targets by evaluating company performance.
- Use demographic analysis tools to understand market potential in specific regions.
- Explore operational data to assess the health and stability of competitors.


### Gartner

Gartner is a technology research and advisory firm that provides insights on technology trends, market performance, and competitive positioning within the tech industry.

#### Features and Capabilities

- **Tech Industry Insights**: Comprehensive research on technology sectors, emerging trends, and digital innovation.
- **Magic Quadrant**: A tool that visually maps companies' strengths and weaknesses within the tech market, ranking competitors based on their vision and execution.
- **Forecasts and Analysis**: Market share forecasts and competitive analysis focused on IT, AI, and digital transformation.
- **Consulting Services**: Access to advisory services for IT strategy and implementation.

#### Applications in Entrepreneurship

Entrepreneurs in tech can use Gartner to:

- Understand where their company or product fits in the broader tech landscape.
- Gain insight into emerging technology trends and potential disruptive innovations.
- Analyze competitors’ strengths and weaknesses through the Magic Quadrant.
- Benchmark their technology against competitors in terms of market readiness and innovation.

#### Ethical and Responsible Use
Gartner provides strategic insights that are valuable but should be used with care. Ensure that data is applied ethically, particularly when evaluating competitors or using proprietary Gartner tools like the Magic Quadrant.



### Louis-Harris Poll

Louis-Harris Poll offers consumer polling data that helps companies understand public opinions on products, services, and brands.

#### Features and Capabilities

- **Consumer Sentiment**: Regularly updated polling data on consumer opinions, behaviors, and trends.
- **Brand Perception**: Insights into how consumers perceive specific brands or product categories.
- **Product Preferences**: Data on consumer preferences for products and services across industries.
- **Public Opinion**: Nationwide surveys on societal issues, marketing trends, and emerging consumer attitudes.

#### Applications in Entrepreneurship

Entrepreneurs can leverage Louis-Harris Poll data to:

- Assess brand perception and public opinion for their own or competitors’ products.
- Understand consumer trends to tailor products and marketing strategies.
- Explore how broader societal trends might impact consumer behavior in their industry.
- Use polling data to support market research and validate product-market fit.

#### Ethical and Responsible Use
Polling data can be highly influential in shaping business decisions, so it’s essential to use it responsibly. Follow BYU’s ethical guidelines when interpreting and applying consumer data in competitive contexts.



### Harris Interactive

Harris Interactive is a market research and consulting firm that specializes in consumer insights, brand tracking, and public opinion polling.

#### Features and Capabilities

- **Consumer Insights**: Provides in-depth data on consumer attitudes and behaviors.
- **Brand Tracking**: Regular tracking of brand performance and public perception across industries.
- **Customized Surveys**: Ability to generate custom survey data tailored to specific market research needs.
- **Public Opinion**: Comprehensive polling on societal issues, brand trust, and consumer trends.

#### Applications in Entrepreneurship

Entrepreneurs can use Harris Interactive to:

- Track how their brand is perceived compared to competitors.
- Generate custom surveys to test new product ideas or marketing campaigns.
- Explore consumer trust and brand loyalty trends in their industry.
- Use polling data to inform marketing strategies and product development.

#### Ethical and Responsible Use
Ensure that consumer data from Harris Interactive is used ethically and transparently. Avoid manipulating polling data and always respect consumer privacy when applying insights to business strategy.



### Capital IQ
Capital IQ, a division of S&P Global, provides financial and market data on public and private companies, enabling detailed financial analysis, valuations, and competitive benchmarking.

#### Features and Capabilities

- **Company Financials**: Comprehensive financial data, including income statements, balance sheets, and cash flow reports.
- **Valuation Tools**: Tools for company valuation, mergers and acquisitions (M&A), and private equity analysis.
- **Industry Data**: Industry-specific metrics, ratios, and benchmarks for competitive analysis.
- **Screening**: Advanced screening tools to find companies or investments that meet specific criteria.

#### Applications in Entrepreneurship
Entrepreneurs can leverage Capital IQ to:

- Analyze competitors' financial health and market position.
- Conduct in-depth financial valuations to support fundraising efforts.
- Research potential acquisition targets or partnership opportunities.
- Benchmark their company's performance against industry standards.

#### Ethical and Responsible Use
Capital IQ offers extensive financial data, which should be used in compliance with legal and ethical standards. Entrepreneurs must avoid using this data inappropriately, especially in M&A scenarios or when analyzing competitors.





<br>

## Product and Market Trends

--- 

### Mintel

Mintel provides in-depth market research reports and consumer insights across a wide range of product categories and industries, with a strong focus on consumer behavior and preferences.

#### Features and Capabilities

- **Market Reports**: Detailed reports on specific product categories, industries, and consumer trends, with global and regional coverage.
- **Consumer Insights**: In-depth analysis of consumer attitudes, preferences, and spending behavior.
- **Trend Analysis**: Long-term and emerging trends that could shape future consumer markets.
- **Custom Surveys**: Mintel offers the ability to design and commission custom consumer surveys.

#### Applications in Entrepreneurship
Entrepreneurs can leverage Mintel data to:

- Understand product category trends and consumer preferences before launching a new product.
- Identify market gaps and emerging trends to develop innovative product solutions.
- Refine marketing strategies by targeting specific consumer segments based on spending habits and preferences.
- Stay ahead of competitors by monitoring how trends evolve over time.


### Ad Age Data Center
Ad Age Data Center provides advertising industry data, including information on advertising expenditures, media buying trends, and competitive ad campaigns.

#### Features and Capabilities

- **Ad Spending Data**: Information on advertising expenditures across industries and media platforms.
- **Media Buying Trends**: Analysis of how companies allocate their advertising budgets across digital, print, TV, and other platforms.
- **Competitive Ad Insights**: Data on how companies structure their ad campaigns, including timing, budgets, and messaging.
- **Top Advertisers and Agencies**: Lists of the top companies and agencies based on advertising spend.

#### Applications in Entrepreneurship
Entrepreneurs can use Ad Age Data Center to:

- Analyze competitors’ advertising strategies and spending to inform their own marketing approaches.
- Monitor media buying trends to optimize their ad spend across platforms.
- Identify top-performing advertisers and agencies in their industry for potential partnerships or benchmarking.
- Refine their marketing mix by aligning it with industry ad spend data.

#### Ethical and Responsible Use
Ad Age provides valuable insights into advertising strategies. Entrepreneurs should ensure that data is used ethically, particularly when analyzing competitors’ ad campaigns. Avoid using the data to misrepresent competitor strategies or make unethical comparisons in marketing efforts.


### eMarketer
eMarketer provides data and analysis on digital marketing, e-commerce, and consumer behavior, offering insights into how businesses and consumers engage with digital platforms.

#### Features and Capabilities

- **Digital Marketing Trends**: Analysis of the latest trends in digital marketing, social media, and advertising.
- **E-Commerce Data**: Comprehensive data on consumer e-commerce behavior, online shopping trends, and digital sales performance.
- **Consumer Behavior Insights**: Data on how consumers engage with digital platforms, including mobile, social media, and video consumption.
- **Ad Spending**: Data on digital ad spending across platforms, including search, social, and display advertising.

#### Applications in Entrepreneurship
Entrepreneurs can use eMarketer to:

- Stay on top of the latest trends in digital marketing and e-commerce to optimize their online presence.
- Analyze consumer behavior on digital platforms to refine marketing and product strategies.
- Benchmark their digital ad spend against industry averages to ensure they are maximizing their budget.
- Identify opportunities in e-commerce growth, particularly in emerging platforms or technologies.

#### Ethical and Responsible Use
eMarketer provides valuable data that should be used in alignment with ethical research practices. Ensure that digital marketing data is not misused to manipulate consumer perceptions and that it is applied responsibly to enhance business strategy.


### Euromonitor International Passport
Euromonitor International Passport is a global market research tool that provides insights into consumer markets, industries, and economies worldwide.

#### Features and Capabilities

- **Market Reports**: Comprehensive reports on industries, economies, and consumer trends in various regions.
- **Consumer Data**: Detailed consumer demographic and spending data across product categories.
- **Industry Forecasts**: Projections for market growth, consumer demand, and economic conditions.
- **Global Coverage**: Data covering hundreds of industries and markets across over 100 countries.

#### Applications in Entrepreneurship
Entrepreneurs can use Euromonitor Passport to:

- Identify growth opportunities in international markets by analyzing consumer spending trends.
- Explore product categories with high demand in specific regions or countries.
- Forecast future market conditions and consumer demand to guide strategic decisions.
- Understand competitive dynamics in global markets and refine product positioning.

#### Ethical and Responsible Use
Euromonitor’s market data is a powerful resource for global market analysis. Ensure that proprietary data is used ethically, particularly in competitive markets, and comply with all legal restrictions on data usage.


-----

## Conclusion

Data is critical for making informed decisions. The private data sources covered in this chapter provide entrepreneurs with invaluable insights across a wide array of business functions, from analyzing industry trends to understanding consumer behavior, tracking competitors, and monitoring market movements. Leveraging these tools effectively can help entrepreneurs anticipate challenges, uncover opportunities, and refine their strategies to stay competitive.

However, with great access comes great responsibility. It is essential to apply the data ethically and responsibly, adhering to institutional guidelines and ensuring that data is used to enhance rather than manipulate business practices. By doing so, entrepreneurs can harness the full potential of these resources to build sustainable, innovative businesses that thrive in their industries.

